# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: opn.com
    CA:
       # Hostname: ca # implicitly ca.org1.example.com
        Country: JO
        Province: Amman
        Locality: Amman
        OrganizationalUnit: OPN
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer1
        SANS:
          - 34.93.54.97
      - Hostname: orderer2
        SANS: 
          - 34.93.54.97      
      - Hostname: orderer3
        SANS: 
          - 34.93.54.97      
      - Hostname: orderer4
        SANS: 
          - 34.93.54.97      
      - Hostname: orderer5
        SANS: 
          - 34.93.54.97

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # ArabAe
  # ---------------------------------------------------------------------------
  - Name: ArabAE
    Domain: arabae.opn.com
    EnableNodeOUs: true
    # "CA"
    # ---------------------------------------------------------------------------
    # Uncomment this section to enable the explicit definition of the CA for this
    # organization.  This entry is a Spec.  See "Specs" section below for details.
    # ---------------------------------------------------------------------------
    CA:
       # Hostname: ca # implicitly ca.org1.example.com
        Country: UAE
        Province: Dubai
        Locality: Dubai
        OrganizationalUnit: OPN
        #StreetAddress: 
        #PostalCode: postalCode for org # default nil
 
    # "Specs"
    # ---------------------------------------------------------------------------
    # Uncomment this section to enable the explicit definition of hosts in your
    # configuration.  Most users will want to use Template, below
    #
    # Specs is an array of Spec entries.  Each Spec entry consists of two fields:
    #   - Hostname:   (Required) The desired hostname, sans the domain.
    #   - CommonName: (Optional) Specifies the template or explicit override for
    #                 the CN.  By default, this is the template:
    #
    #                              "{{.Hostname}}.{{.Domain}}"
    #
    #                 which obtains its values from the Spec.Hostname and
    #                 Org.Domain, respectively.
    #   - SANS:       (Optional) Specifies one or more Subject Alternative Names
    #                 to be set in the resulting x509. Accepts template
    #                 variables {{.Hostname}}, {{.Domain}}, {{.CommonName}}. IP
    #                 addresses provided here will be properly recognized. Other
    #                 values will be taken as DNS names.
    #                 NOTE: Two implicit entries are created for you:
    #                     - {{ .CommonName }}
    #                     - {{ .Hostname }}
    # ---------------------------------------------------------------------------
    # Specs:
    #   - Hostname: foo # implicitly "foo.org1.example.com"
    #     CommonName: foo27.org5.example.com # overrides Hostname-based FQDN set above
    #     SANS:
    #       - "bar.{{.Domain}}"
    #       - "altfoo.{{.Domain}}"
    #       - "{{.Hostname}}.org6.net"
    #       - 172.16.10.31
    #   - Hostname: bar
    #   - Hostname: baz

    # ---------------------------------------------------------------------------
    # "Template"
    # ---------------------------------------------------------------------------
    # Allows for the definition of 1 or more hosts that are created sequentially
    # from a template. By default, this looks like "peer%d" from 0 to Count-1.
    # You may override the number of nodes (Count), the starting index (Start)
    # or the template used to construct the name (Hostname).
    #
    # Note: Template and Specs are not mutually exclusive.  You may define both
    # sections and the aggregate nodes will be created for you.  Take care with
    # name collisions
    # ---------------------------------------------------------------------------

    Template:
      Count: 2
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
      # SANS:
      #   - "{{.Hostname}}.alt.{{.Domain}}"    
      SANS:
          - 158.176.67.250
          - "{{.Hostname}}-arabae"

    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # ArabJO: See "ArabAE" for full specification
  # ---------------------------------------------------------------------------
  - Name: ArabJO
    Domain: arabjo.opn.com
    EnableNodeOUs: true
    CA:
       # Hostname: ca # implicitly ca.org1.example.com
        Country: JO
        Province: Amman
        Locality: Amman
        OrganizationalUnit: OPN
    Template:
      Count: 2
      SANS:
          - 158.176.67.247
          - "{{.Hostname}}-arabjo"
    Users:
      Count: 1

  # ---------------------------------------------------------------------------
  # ABTreasury: See "ArabAE" for full specification
  # ---------------------------------------------------------------------------
  - Name: ABTreasury
    Domain: abtreasury.opn.com
    EnableNodeOUs: true
    CA:
       # Hostname: ca # implicitly ca.org1.example.com
        Country: JORDAN
        Province: Amman
        Locality: Amman
        OrganizationalUnit: OPN    
    Template:
      Count: 2
      SANS:
          - 158.176.67.249      
    Users:
      Count: 1
